version: '3'

services:
  db:
    image: mysql:5.6.49
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: opencart
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/config:/etc/mysql/conf.d
      - ./mysql/log:/etc/logs
      - ./mysql/data:/var/lib/mysql

  web:
    build: .
    # image: php:7.3.21-apache-buster
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./upload:/var/www/html/
    ports:
      - "8080:80"
    stdin_open: true
    tty: true